.TH "expression" 3 "Fri Jun 24 2022" "Version 1.0" "Moolang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
expression
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBtoken\fP \fBoperator\fP"
.br
.ti -1c
.RI "struct \fBexpression\fP * \fBleft\fP"
.br
.ti -1c
.RI "struct \fBexpression\fP * \fBright\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Moolang from the source code\&.
