.TH "src/main.c" 3 "Sun Jul 3 2022" "Version 1.0" "Moolang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include 'scanner/scanner\&.h'\fP
.br
\fC#include 'parser/parser\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
A programming language 
.SH "Author"
.PP 
Generated automatically by Doxygen for Moolang from the source code\&.
