.TH "src/parser/parser.h" 3 "Sun Jul 3 2022" "Version 1.0" "Moolang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parser/parser.h
.SH SYNOPSIS
.br
.PP
\fC#include 'error\&.h'\fP
.br
\fC#include 'expression\&.h'\fP
.br
\fC#include 'src/scanner/scanner\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCURRENT_LINE\fP   *CURRENT_TOKEN\&.line"
.br
.ti -1c
.RI "#define \fBCURRENT_TOKEN\fP   &parser_tokens\&.array[0]"
.br
.ti -1c
.RI "#define \fBCURRENT_TOKEN_IS\fP(\&.\&.\&.)   	\fB__TOKEN_IS__\fP(CURRENT_TOKEN, (TokenType[]){__VA_ARGS__, \-1})"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBexpression\fP * \fBparse\fP (struct \fBscan\fP *s)"
.br
.ti -1c
.RI "struct \fBtoken\fP \fBparser_advance\fP ()"
.br
.ti -1c
.RI "int \fB__TOKEN_IS__\fP (const struct \fBtoken\fP *tok, const TokenType type[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBtoken_array\fP \fBparser_tokens\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The root file of the parser library\&.
.br
 It declares functions related to the \fBsource\fP file's global \fBtoken_array\fP\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CURRENT_TOKEN_IS( \&.\&.\&.)   	\fB__TOKEN_IS__\fP(CURRENT_TOKEN, (TokenType[]){__VA_ARGS__, \-1})"
Variadic-length macro comparing the current token with every token given as an argument\&.
.br
 Calls \fB__TOKEN_IS__()\fP\&. 
.SH "Function Documentation"
.PP 
.SS "int __TOKEN_IS__ (const struct \fBtoken\fP * tok, const TokenType type[])"
Used by the variadic-length macro \fBCURRENT_TOKEN_IS\fP\&.
.br
 Do not use this function manually\&.
.PP
\fBParameters\fP
.RS 4
\fITok\fP \fBtoken\fP to be compared\&. 
.br
\fIType\fP \fBtoken\fP's to be compared to\&.
.br
 Array finishes with a non-token value, and is generated by the macro \fBCURRENT_TOKEN_IS\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
1 if \fBtok\fP is a token found in \fBtype\fP\&.
.br
 0 if \fBtok\fP is not a token found in \fBtype\fP\&. 
.RE
.PP

.SS "struct \fBexpression\fP* parse (struct \fBscan\fP * s)"
The parser's main function\&. 
.PP
\fBParameters\fP
.RS 4
\fIS\fP The scanned source code and the token arrays\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The program's abstract syntax tree\&. 
.RE
.PP

.SS "struct \fBtoken\fP parser_advance ()"
Advance \fBparser_tokens\fP\&. 
.PP
\fBReturns\fP
.RS 4
Token: The \fBtoken\fP that was advanced by\&. 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "struct \fBtoken_array\fP parser_tokens\fC [extern]\fP"
global \fBtoken_array\fP used to orchestrate the rest of the library\&.
.br
 Gets manipulated by the \fBparser_advance()\fP function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Moolang from the source code\&.
