.TH "source" 3 "Sun Jul 3 2022" "Version 1.0" "Moolang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstring\fP"
.br
.ti -1c
.RI "const char * \fBfile_name\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBfile_descriptor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Moolang from the source code\&.
