.TH "token" 3 "Sat Jun 25 2022" "Version 1.0" "Moolang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
token
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsubstring\fP \fBlexeme\fP"
.br
.ti -1c
.RI "TokenType \fBtype\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Moolang from the source code\&.
